---
- name: install apache2 on redhat
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: yes
  changed_when: true
  notify: Restart service

- name: copying the config file on redhat
  ansible.builtin.copy:
    content: apache2.conf.j2
    dest: "{{ config_httpd }}"
  changed_when: true
  notify: Restart service